- name: Replace skk.xml # ibus-skkは独自のキーボード配列設定を持っていて、デフォルトが日本語
  become: yes
  replace:
    path: /usr/share/ibus/component/skk.xml
    regexp: "<layout>jp</layout>"
    replace: "<layout>us</layout>"
    backup: yes

- name: Add .xprofile settings
  blockinfile:
    path: "{{ ansible_env.HOME }}/.xprofile"
    create: yes
    block: |
      export LANG="ja_JP.UTF-8"
      export XMODIFIERS="@im=ibus"
      export XMODIFIER="@im=ibus"
      export GTK_IM_MODULE=ibus
      export QT_IM_MODULE=ibus
      export DefaultIMModule=ibus
      ibus-daemon -drx
